// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelProcessing():Promise<boolean>;

export function ExportTxt(arg1:string):Promise<string>;

export function ExportXlsx(arg1:string):Promise<string>;

export function ExtractAssets(arg1:string,arg2:boolean):Promise<main.AssetExtractionResult>;

export function GetCounters():Promise<main.Counters>;

export function GetProcessingResult():Promise<main.ProcessResult>;

export function GetProcessingState():Promise<main.ProcessingState>;

export function LoadBlacklist(arg1:string):Promise<Array<string>>;

export function LoadConfig():Promise<main.AppConfig>;

export function LoadWhitelist(arg1:string):Promise<Array<string>>;

export function ParseCSVFile(arg1:string):Promise<Array<string>>;

export function ParseExcelFile(arg1:string):Promise<Array<string>>;

export function ParseURLFile(arg1:string):Promise<Array<string>>;

export function PauseProcessing():Promise<boolean>;

export function ProcessURLs(arg1:string,arg2:main.ProcessOptions):Promise<main.ProcessResult>;

export function ResumeProcessing():Promise<boolean>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SetBlacklist(arg1:Array<string>):Promise<void>;

export function SetWhitelist(arg1:Array<string>):Promise<void>;

export function StartProcessing(arg1:string,arg2:main.ProcessOptions):Promise<void>;
