// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportTxt(arg1:string):Promise<string>;

export function ExportXlsx(arg1:string):Promise<string>;

export function GetCounters():Promise<main.Counters>;

export function LoadBlacklist(arg1:string):Promise<Array<string>>;

export function LoadWhitelist(arg1:string):Promise<Array<string>>;

export function ParseExcelFile(arg1:string):Promise<Array<string>>;

export function ParseURLFile(arg1:string):Promise<Array<string>>;

export function ProcessURLs(arg1:string,arg2:main.ProcessOptions):Promise<main.ProcessResult>;

export function SetBlacklist(arg1:Array<string>):Promise<void>;

export function SetWhitelist(arg1:Array<string>):Promise<void>;
