// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportTxt(arg1) {
  return window['go']['main']['App']['ExportTxt'](arg1);
}

export function ExportXlsx(arg1) {
  return window['go']['main']['App']['ExportXlsx'](arg1);
}

export function GetCounters() {
  return window['go']['main']['App']['GetCounters']();
}

export function LoadBlacklist(arg1) {
  return window['go']['main']['App']['LoadBlacklist'](arg1);
}

export function LoadWhitelist(arg1) {
  return window['go']['main']['App']['LoadWhitelist'](arg1);
}

export function ParseExcelFile(arg1) {
  return window['go']['main']['App']['ParseExcelFile'](arg1);
}

export function ParseURLFile(arg1) {
  return window['go']['main']['App']['ParseURLFile'](arg1);
}

export function ProcessURLs(arg1, arg2) {
  return window['go']['main']['App']['ProcessURLs'](arg1, arg2);
}

export function SetBlacklist(arg1) {
  return window['go']['main']['App']['SetBlacklist'](arg1);
}

export function SetWhitelist(arg1) {
  return window['go']['main']['App']['SetWhitelist'](arg1);
}
