// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelProcessing() {
  return window['go']['main']['App']['CancelProcessing']();
}

export function ExportTxt(arg1) {
  return window['go']['main']['App']['ExportTxt'](arg1);
}

export function ExportXlsx(arg1) {
  return window['go']['main']['App']['ExportXlsx'](arg1);
}

export function ExtractAssets(arg1, arg2) {
  return window['go']['main']['App']['ExtractAssets'](arg1, arg2);
}

export function GetCounters() {
  return window['go']['main']['App']['GetCounters']();
}

export function GetProcessingResult() {
  return window['go']['main']['App']['GetProcessingResult']();
}

export function GetProcessingState() {
  return window['go']['main']['App']['GetProcessingState']();
}

export function LoadBlacklist(arg1) {
  return window['go']['main']['App']['LoadBlacklist'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadTscanPlusResult() {
  return window['go']['main']['App']['LoadTscanPlusResult']();
}

export function LoadWhitelist(arg1) {
  return window['go']['main']['App']['LoadWhitelist'](arg1);
}

export function ParseCSVFile(arg1) {
  return window['go']['main']['App']['ParseCSVFile'](arg1);
}

export function ParseExcelFile(arg1) {
  return window['go']['main']['App']['ParseExcelFile'](arg1);
}

export function ParseURLFile(arg1) {
  return window['go']['main']['App']['ParseURLFile'](arg1);
}

export function PauseProcessing() {
  return window['go']['main']['App']['PauseProcessing']();
}

export function ProcessURLs(arg1, arg2) {
  return window['go']['main']['App']['ProcessURLs'](arg1, arg2);
}

export function ResumeProcessing() {
  return window['go']['main']['App']['ResumeProcessing']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetBlacklist(arg1) {
  return window['go']['main']['App']['SetBlacklist'](arg1);
}

export function SetWhitelist(arg1) {
  return window['go']['main']['App']['SetWhitelist'](arg1);
}

export function StartProcessing(arg1, arg2) {
  return window['go']['main']['App']['StartProcessing'](arg1, arg2);
}
